spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes[0]:
        uri: https://localhost:8080/dev/auth
        id: LoginService
        predicates[0]: Path=/dev/auth/**
      routes[1]:
        id: Admin
        predicates[0]: Path=/dev/category/**
        uri: https://localhost:8084/dev/category
      routes[2]:
        id: Admin
        uri: https://localhost:8084/dev/admin/profile
        predicates[0]: Path=/dev/admin/profile/**
      routes[3]:
        predicates[0]: Path=/dev/admin/**
        id: Admin
        uri: https://localhost:8084/dev/admin
      routes[4]:
        uri: https://localhost:8084/dev/subcategory
        id: Admin
        predicates[0]: Path=/dev/subcategory/**
      routes[5]:
        uri: https://localhost:8084/dev/specification
        id: Admin
        predicates[0]: Path=/dev/specification/**
      routes[6]:
        uri: https://localhost:8084/dev/productMeasurement
        id: Admin
        predicates[0]: Path=/dev/productMeasurement/**
      routes[7]:
        uri: https://localhost:8084/dev/product
        id: Admin
        predicates[0]: Path=/dev/product/**
      routes[8]:
        uri: https://localhost:8084/dev/adminMData
        id: Admin
        predicates[0]: Path=/dev/adminMData/**
      routes[9]:
        uri: https://localhost:8083/dev/designerProduct
        id: Designer
        predicates[0]: Path=/dev/designerProduct/**
      routes[10]:
        uri: https://localhost:8083/dev/designer
        id: Designer
        predicates[0]: Path=/dev/designer/**
      routes[11]:
        uri: https://localhost:8083/dev/orderStatus
        id: Designer
        predicates[0]: Path=/dev/orderStatus/**
      routes[12]:
        uri: https://localhost:8082/dev/user
        id: User
        predicates[0]: Path=/dev/user/**
      routes[13]:
        uri: https://localhost:8082/dev/userOrder
        id: User
        predicates[0]: Path=/dev/userOrder/**
      routes[14]:
        uri: https://localhost:8083/dev/order
        id: Designer
        predicates[0]: Path=/dev/order/**
      routes[15]:
        uri: https://localhost:8084/dev/hsn
        id: Admin
        predicates[0]: Path=/dev/hsn/**
#      routes[16]:
#        uri: https://localhost:8085/dev/measurement
#        id: Designer
#        predicates[0]: Path=/dev/measurement/**
      routes[16]:
        uri: https://localhost:8083/dev/designerProducts
        id: Designer
        predicates[0]: Path=/dev/designerProducts/**
      routes[17]:
        uri: https://localhost:8082/dev/userMeasurement
        id: User
        predicates[0]: Path=/dev/userMeasurement/**
      routes[18]:
        uri: https://localhost:8084/dev/account
        id: Admin
        predicates[0]: Path=/dev/account/**
      routes[19]:
        uri: https://localhost:8083/dev/designerAccount
        id: Designer
        predicates[0]: Path=/dev/designerAccount/**
        
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-headers: '*'
            allowedMethods: GET, POST, PUT, DELETE
            max-age: '3600'
            allowed-origins: '*'
  profiles: dev
  application:
    name: ApiGatway
server:
  port: 9095
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt
    key-store-password: Divatt
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
---
spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes[0]:
        uri: https://localhost:9091/prod/auth
        id: LoginService
        predicates[0]: Path=/prod/auth/**
      routes[1]:
        id: Admin
        predicates[0]: Path=/prod/category/**
        uri: https://localhost:9093/prod/category
      routes[2]:
        id: Admin
        uri: https://localhost:9093/prod/admin/profile
        predicates[0]: Path=/prod/admin/profile/**
      routes[3]:
        predicates[0]: Path=/prod/admin/**
        id: Admin
        uri: https://localhost:9093/prod/admin
      routes[4]:
        uri: https://localhost:9093/prod/subcategory
        id: Admin
        predicates[0]: Path=/prod/subcategory/**
      routes[5]:
        uri: https://localhost:9093/prod/specification
        id: Admin
        predicates[0]: Path=/prod/specification/**
      routes[6]:
        uri: https://localhost:9093/prod/productMeasurement
        id: Admin
        predicates[0]: Path=/prod/productMeasurement/**
      routes[7]:
        uri: https://localhost:9093/prod/product
        id: Admin
        predicates[0]: Path=/prod/product/**
      routes[8]:
        uri: https://localhost:9093/prod/adminMData
        id: Admin
        predicates[0]: Path=/prod/adminMData/**
      routes[9]:
        uri: https://localhost:9094/prod/designerProduct
        id: Designer
        predicates[0]: Path=/prod/designerProduct/**
      routes[10]:
        uri: https://localhost:9094/prod/designer
        id: Designer
        predicates[0]: Path=/prod/designer/**
      routes[11]:
        uri: https://localhost:9094/prod/orderStatus
        id: Designer
        predicates[0]: Path=/prod/orderStatus/**
      routes[12]:
        uri: https://localhost:9092/prod/user
        id: User
        predicates[0]: Path=/prod/user/**
      routes[13]:
        uri: https://localhost:9092/prod/userOrder
        id: User
        predicates[0]: Path=/prod/userOrder/**
      routes[14]:
        uri: https://localhost:9094/prod/order
        id: Designer
        predicates[0]: Path=/prod/order/**
      routes[15]:
        uri: https://localhost:9093/prod/hsn
        id: Admin
        predicates[0]: Path=/prod/hsn/**
      routes[16]:
        uri: https://localhost:9094/prod/designerProducts
        id: Designer
        predicates[0]: Path=/prod/designerProducts/**
      routes[17]:
        uri: https://localhost:9092/prod/userMeasurement
        id: User
        predicates[0]: Path=/prod/userMeasurement/**
      routes[18]:
        uri: https://localhost:9093/prod/account
        id: Admin
        predicates[0]: Path=/prod/account/**
      routes[19]:
        uri: https://localhost:8083/prod/designerAccount
        id: Designer
        predicates[0]: Path=/prod/designerAccount/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-headers: '*'
            allowedMethods: GET, POST, PUT, DELETE
            max-age: '3600'
            allowed-origins: '*'
  profiles: prod
  application:
    name: ApiGatway
server:
  port: 9090
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt
    key-store-password: Divatt
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      

---      
spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes[0]:
        uri: https://localhost:8080/default/auth
        id: LoginService
        predicates[0]: Path=/default/auth/**
      routes[1]:
        id: Admin
        predicates[0]: Path=/default/category/**
        uri: https://localhost:8084/default/category
      routes[2]:
        id: Admin
        uri: https://localhost:8084/default/admin/profile
        predicates[0]: Path=/default/admin/profile/**
      routes[3]:
        predicates[0]: Path=/default/admin/**
        id: Admin
        uri: https://localhost:8084/default/admin
      routes[4]:
        uri: https://localhost:8084/default/subcategory
        id: Admin
        predicates[0]: Path=/default/subcategory/**
      routes[5]:
        uri: https://localhost:8084/default/specification
        id: Admin
        predicates[0]: Path=/default/specification/**
      routes[6]:
        uri: https://localhost:8084/default/productMeasurement
        id: Admin
        predicates[0]: Path=/default/productMeasurement/**
      routes[7]:
        uri: https://localhost:8084/default/product
        id: Admin
        predicates[0]: Path=/default/product/**
      routes[8]:
        uri: https://localhost:8084/default/adminMData
        id: Admin
        predicates[0]: Path=/default/adminMData/**
      routes[9]:
        uri: https://localhost:8083/default/designerProduct
        id: Designer
        predicates[0]: Path=/default/designerProduct/**
      routes[10]:
        uri: https://localhost:8083/default/designer
        id: Designer
        predicates[0]: Path=/default/designer/**
      routes[11]:
        uri: https://localhost:8083/default/orderStatus
        id: Designer
        predicates[0]: Path=/default/orderStatus/**
      routes[12]:
        uri: https://localhost:8082/default/user
        id: User
        predicates[0]: Path=/default/user/**
      routes[13]:
        uri: https://localhost:8082/default/userOrder
        id: User
        predicates[0]: Path=/default/userOrder/**
      routes[14]:
        uri: https://localhost:8083/default/order
        id: Designer
        predicates[0]: Path=/default/order/**
      routes[15]:
        uri: https://localhost:8084/default/hsn
        id: Admin
        predicates[0]: Path=/default/hsn/**
#      routes[16]:
#        uri: https://localhost:8085/default/measurement
#        id: Designer
#        predicates[0]: Path=/default/measurement/**
      routes[16]:
        uri: https://localhost:8083/default/designerProducts
        id: Designer
        predicates[0]: Path=/default/designerProducts/**
      routes[17]:
        uri: https://localhost:8082/default/userMeasurement
        id: User
        predicates[0]: Path=/default/userMeasurement/**
      routes[18]:
        uri: https://localhost:8084/default/account
        id: Admin
        predicates[0]: Path=/default/account/**
      routes[19]:
        uri: https://localhost:8083/default/designerAccount
        id: Designer
        predicates[0]: Path=/default/designerAccount/**
        
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-headers: '*'
            allowedMethods: GET, POST, PUT, DELETE
            max-age: '3600'
            allowed-origins: '*'
  profiles: default
  application:
    name: ApiGatway
server:
  port: 9095
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt 
    key-store-password: Divatt
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
