version: '3.1'
# docker network
networks:
  app-nw:
# for admin
services:
  admin:
    build: 
      context: admin-service
      dockerfile: Dockerfile.admin
    ports:
     - "8084:8084"
    networks:
    - app-nw
# for designer
  designer:
    build: 
      context: esigner-service
      dockerfile: Dockerfile.designer
    ports:
    - "8083:8083"
    networks:
    - app-nw
# for gateway
  gateway-server:
    build:
      context: gateway-server
      dockerfile: Dockerfile.gateway
    ports:
    - "9095:9095"
    networks:
    - app-nw
# for login
  login:
    build:
      context: login-service
      dockerfile: Dockerfile.login
    ports:
    - "8080:8080"
    networks:
    - app-nw
# for registry
  registry:
    build:
      context: registry-sever
      dockerfile: Dockerfile.registry
    ports:
    - "8761:8761"
    networks:
    - app-nw
# for user
  user:
    build:
      context: user-service
      dockerfile: Dockerfile.user
    ports:
    - "8082:8082"
    networks:
    - app-nw
