version: '3.2'
# docker network
networks:
  app-nw:
# for admin
services:
  admin:
    build: 
      contest: admin-service
      dockerfile: Dockerfile.admin
    ports:
     - "8084:8084"
    networks:
    - app-nw
# for designer
  designer:
    build: 
      contest: designer-service
      dockerfile: Dockerfile.designer
    ports:
    - "8083:8083"
    networks:
    - app-nw
# for gateway
  gateway:
    build:
      contest: gateway
      dockerfile: Dockerfile.gateway
    ports:
    - "9095:9095"
    networks:
    - app-nw
# for login
  login:
    build:
      contest: auth
      dockerfile: Dockerfile.login
    ports:
    - "8080:8080"
    networks:
    - app-nw
# for registry
  registry:
    build:
      contest: registry
      dockerfile: Dockerfile.registry
    ports:
    - "8761:8761"
    networks:
    - app-nw
# for user
  user:
    build:
      contest: user-service
      dockerfile: Dockerfile.user
    ports:
    - "8082:8082"
    networks:
    - app-nw
