spring:
  profiles: default
  application: 
     name: Designer 
  data:
    mongodb:
      database: divatt
      host: localhost
      port: 27017
      username: test
 
server: 
  port: 8083
  servlet: 
    contextPath: /default
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt
    key-store-password: Divatt
    enabled: true
name: default-yml
environment: default
enabled: true
contextpath: /default
servers: 
   - www.default.com
   - www.default1.com
logging: 
      file: 
        name: logs/designer_default_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.daivatt.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 2592000000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: dev
  application: 
     name: Designer
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195
      password: word_pass
      port: 27017
      username: dbuser 
 
server: 
  port: 8083
  servlet: 
    contextPath: /dev
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt
    key-store-password: Divatt
    enabled: true
name: dev-yml
environment: dev
enabled: true
contextpath: /dev
servers: 
   - www.dev.com
   - www.dev1.com
logging: 
      file: 
        name: logs/designer_dev_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.daivatt.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 2592000000

connection: 
  pool: 
    initialPoolSize: 5
    minPoolSize: 10
    maxPoolSize: 20
    maxIdleTime: 3000
    
spring.servlet.multipart:
  enabled: true
  max-file-size: 100MB
file.upload-path: /home/ubuntu/Attachment/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#AWS properties
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      accessKey: AKIA3UEGY4UHZ77545ME
      secretKey: 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

application:
  bucket:
    name: divatt-uat
    basepath: D-App
---
spring:
  profiles: prod
  application: 
     name: Designer
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195
      password: word_pass
      port: 27017
      username: dbuser 
 
server: 
  port: 9094
  servlet: 
    contextPath: /prod
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt
    key-store-password: Divatt
    enabled: true
name: prod-yml
environment: prod
enabled: true
contextpath: /prod
servers: 
   - www.prod.com
   - www.prod1.com
logging: 
      file: 
        name: logs/designer_prod_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.daivatt.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 2592000000

connection: 
  pool: 
    initialPoolSize: 5
    minPoolSize: 10
    maxPoolSize: 20
    maxIdleTime: 3000
    
spring.servlet.multipart:
  enabled: true
  max-file-size: 100MB
file.upload-path: /home/ubuntu/Attachment/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#AWS properties
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      accessKey: AKIA3UEGY4UHZ77545ME
      secretKey: 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

application:
  bucket:
    name: divatt-uat
    basepath: D-App