spring:
  profiles: default
  application: 
     name: User
  data:
    mongodb:
      database: divatt
      host: localhost
      port: 27017
      username: test 
 
server: 
  port: 8082
  servlet: 
    contextPath: /default
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt
    key-store-password: Divatt
    enabled: true
name: default-yml
environment: default
enabled: true
contextpath: /default
servers: 
   - www.default.com
   - www.default1.com
logging: 
      file: 
        name: logs/user_default_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.daivatt.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 2592000000
mail.from: no-reply@divatt.com

---
spring:
  profiles: dev
  application: 
     name: User 
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195
      password: word_pass
      port: 27017
      username: dbuser 
 
server: 
  port: 8082
  servlet: 
    contextPath: /dev
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt
    key-store-password: Divatt
    enabled: true
name: dev-yml
environment: dev
enabled: true
contextpath: /dev
servers: 
   - www.dev.com
   - www.dev1.com
logging: 
      file: 
        name: logs/user_dev_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.daivatt.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 2592000000
mail.from: no-reply@divatt.com


---
spring:
  profiles: prod
  application: 
     name: User 
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195
      password: word_pass
      port: 27017
      username: dbuser 
 
server: 
  port: 9092
  servlet: 
    contextPath: /prod
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt
    key-store-password: Divatt
    enabled: true
name: prod-yml
environment: prod
enabled: true
contextpath: /prod
servers: 
   - www.prod.com
   - www.prod1.com
logging: 
      file: 
        name: logs/user_prod_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.daivatt.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 2592000000
mail.from: no-reply@divatt.com