spring:
  profiles: default
  application: 
     name: LoginService 
  data:
    mongodb:
      database: divatt
      host: localhost
      port: 27017
      username: test
 
server: 
  port: 8080
  servlet: 
    contextPath: /default
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt
    key-store-password: Divatt
    enabled: true
name: default-yml
environment: default
enabled: true
contextpath: /default
servers: 
   - www.default.com
   - www.default1.com
logging: 
      file: 
        name: logs/auth_default_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.ulearn.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 2592000000
mail.from: no-reply@divatt.com
cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA3UEGY4UH7Z5FE3KU
      secret-key: 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
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: dev
  application: 
     name: LoginService 
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195
      password: word_pass
      port: 27017
      username: dbuser 
 
server: 
  port: 8080
  servlet: 
    contextPath: /dev
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt
    key-store-password: Divatt

name: dev-yml
environment: dev
enabled: true
contextpath: /dev
servers: 
   - www.dev.com
   - www.dev1.com
logging: 
      file: 
        name: logs/auth_dev_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.ulearn.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 2592000000
mail.from: no-reply@divatt.com
cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA3UEGY4UH7Z5FE3KU
      secret-key: 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
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  profiles: prod
  application: 
     name: LoginService 
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195
      password: word_pass
      port: 27017
      username: dbuser 
 
server: 
  port: 8080
  servlet: 
    contextPath: /prod
  ssl:
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-alias: local_ssl
    key-password: Divatt
    key-store-password: Divatt

name: prod-yml
environment: prod
enabled: true
contextpath: /prod
servers: 
   - www.prod.com
   - www.prod1.com
logging: 
      file: 
        name: logs/auth_prod_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.ulearn.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 2592000000
mail.from: no-reply@divatt.com
cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA3UEGY4UH7Z5FE3KU
      secret-key: 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
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka